import type { ComponentProps, ReactNode } from 'react'
import type { ThumbnailImage } from './thumbnails'

import {
  AlertDialog, BufferingIndicator, CastButton, Container, Controls, ErrorDialog,
  FullscreenButton, Gesture, Hotkey, Menu, MuteButton, PiPButton, PlayButton,
  PlaybackRateMenu, Popover, SeekIndicator, Slider, StatusAnnouncer,
  StatusIndicator, Time, TimeSlider, Tooltip, VolumeIndicator, VolumeSlider,
  usePlaybackRateMenu, usePlayer,
} from '@videojs/react'
import {
  CaptionsOffIcon, CaptionsOnIcon, CastEnterIcon, CastExitIcon, CheckIcon,
  ChevronIcon, FullscreenEnterIcon, FullscreenExitIcon, PauseIcon, PipEnterIcon,
  PipExitIcon, PlayIcon, RestartIcon, SpinnerIcon, VolumeHighIcon,
  VolumeLowIcon, VolumeOffIcon,
} from '@videojs/react/icons'

const SEEK_TIME = 10

const Button = ({ className, ...props }: ComponentProps<'button'>) => (
  <button type="button" className={['media-button media-button--subtle media-button--icon', className].filter(Boolean).join(' ')} {...props} />
)

const VolumePopover = () => {
  const volumeUnsupported = usePlayer((s) => s.volumeAvailability === 'unsupported')
  const muteButton = (
    <MuteButton className="media-button--mute" render={<Button />}>
      <VolumeOffIcon className="media-icon media-icon--volume-off" />
      <VolumeLowIcon className="media-icon media-icon--volume-low" />
      <VolumeHighIcon className="media-icon media-icon--volume-high" />
    </MuteButton>
  )
  if (volumeUnsupported) return muteButton
  return (
    <Popover.Root openOnHover delay={200} closeDelay={100} side="top">
      <Popover.Trigger render={muteButton} />
      <Popover.Popup className="media-surface media-popover media-popover--volume">
        <VolumeSlider.Root className="media-slider" orientation="vertical" thumbAlignment="edge">
          <Slider.Track className="media-slider__track">
            <Slider.Fill className="media-slider__fill" />
          </Slider.Track>
          <Slider.Thumb className="media-slider__thumb media-slider__thumb--persistent" />
        </VolumeSlider.Root>
      </Popover.Popup>
    </Popover.Root>
  )
}

const PlaybackRateMenuItems = () => {
  const { options, setValue, value } = usePlaybackRateMenu()
  return (
    <Menu.RadioGroup className="media-menu__group" value={value} onValueChange={setValue} label="Playback rate">
      {options.map((option) => (
        <Menu.RadioItem key={option.value} className="media-menu__item" value={option.value} disabled={option.disabled}>
          <span>{option.label}</span>
          <Menu.ItemIndicator checked={option.value === value} forceMount className="media-menu__indicator">
            <CheckIcon className="media-icon" />
          </Menu.ItemIndicator>
        </Menu.RadioItem>
      ))}
    </Menu.RadioGroup>
  )
}

export type RippleSkinProps = {
  children: ReactNode
  // Extra control-bar entries (e.g. the subtitle menu), right of the rate menu.
  menu?: ReactNode
  // Seekbar hover previews generated by the thumbnail remuxer.
  thumbnails?: ThumbnailImage[]
}

// The @videojs VideoSkin layout, owned by ripple: volume lives next to
// play/pause, the ±10s buttons are gone (hotkeys and gestures still seek), the
// native captions toggle is replaced by the jassub-driven menu slot.
export const RippleSkin = ({ children, menu, thumbnails }: RippleSkinProps) => (
  <Container className="media-default-skin media-default-skin--video">
    {children}
    <BufferingIndicator render={(props) => (
      <div {...props} className="media-buffering-indicator">
        <div className="media-surface"><SpinnerIcon className="media-icon" /></div>
      </div>
    )} />
    <ErrorDialog.Root>
      <AlertDialog.Popup className="media-error">
        <div className="media-error__dialog media-surface">
          <div className="media-error__content">
            <AlertDialog.Title className="media-error__title">Something went wrong.</AlertDialog.Title>
            <ErrorDialog.Description className="media-error__description" />
          </div>
          <div className="media-error__actions">
            <AlertDialog.Close className="media-button media-button--primary">OK</AlertDialog.Close>
          </div>
        </div>
      </AlertDialog.Popup>
    </ErrorDialog.Root>
    <Controls.Root className="media-surface media-controls">
      <Tooltip.Provider>
        <div className="media-button-group">
          <Tooltip.Root side="top">
            <Tooltip.Trigger render={(
              <PlayButton className="media-button--play" render={<Button />}>
                <RestartIcon className="media-icon media-icon--restart" />
                <PlayIcon className="media-icon media-icon--play" />
                <PauseIcon className="media-icon media-icon--pause" />
              </PlayButton>
            )} />
            <Tooltip.Popup className="media-surface media-tooltip" />
          </Tooltip.Root>
          <VolumePopover />
        </div>
        <div className="media-time-controls">
          <Time.Value type="current" className="media-time" />
          <TimeSlider.Root className="media-slider">
            <Slider.Track className="media-slider__track">
              <Slider.Fill className="media-slider__fill" />
              <Slider.Buffer className="media-slider__buffer" />
            </Slider.Track>
            <Slider.Thumb className="media-slider__thumb" />
            <div className="media-surface media-preview media-slider__preview">
              <Slider.Thumbnail className="media-preview__thumbnail" thumbnails={thumbnails} />
              <Slider.Value type="pointer" className="media-time media-preview__time" />
              <SpinnerIcon className="media-preview__spinner media-icon" />
            </div>
          </TimeSlider.Root>
          <Time.Value type="duration" className="media-time" />
        </div>
        <div className="media-button-group">
          <PlaybackRateMenu.Root side="top" align="center">
            <PlaybackRateMenu.Trigger className="media-button--playback-rate" render={<Button />} />
            <PlaybackRateMenu.Content className="media-surface media-popover media-menu media-menu--playback-rate">
              <PlaybackRateMenuItems />
            </PlaybackRateMenu.Content>
          </PlaybackRateMenu.Root>
          {menu}
          <Tooltip.Root side="top">
            <Tooltip.Trigger render={(
              <CastButton className="media-button--cast" render={<Button />}>
                <CastEnterIcon className="media-icon media-icon--cast-enter" />
                <CastExitIcon className="media-icon media-icon--cast-exit" />
              </CastButton>
            )} />
            <Tooltip.Popup className="media-surface media-tooltip" />
          </Tooltip.Root>
          <Tooltip.Root side="top">
            <Tooltip.Trigger render={(
              <PiPButton className="media-button--pip" render={<Button />}>
                <PipEnterIcon className="media-icon media-icon--pip-enter" />
                <PipExitIcon className="media-icon media-icon--pip-exit" />
              </PiPButton>
            )} />
            <Tooltip.Popup className="media-surface media-tooltip" />
          </Tooltip.Root>
          <Tooltip.Root side="top">
            <Tooltip.Trigger render={(
              <FullscreenButton className="media-button--fullscreen" render={<Button />}>
                <FullscreenEnterIcon className="media-icon media-icon--fullscreen-enter" />
                <FullscreenExitIcon className="media-icon media-icon--fullscreen-exit" />
              </FullscreenButton>
            )} />
            <Tooltip.Popup className="media-surface media-tooltip" />
          </Tooltip.Root>
        </div>
      </Tooltip.Provider>
    </Controls.Root>
    <div className="media-overlay" />
    <Hotkey keys="Space" action="togglePaused" />
    <Hotkey keys="k" action="togglePaused" />
    <Hotkey keys="m" action="toggleMuted" />
    <Hotkey keys="f" action="toggleFullscreen" />
    <Hotkey keys="i" action="togglePictureInPicture" />
    <Hotkey keys="ArrowRight" action="seekStep" value={SEEK_TIME / 2} />
    <Hotkey keys="ArrowLeft" action="seekStep" value={-(SEEK_TIME / 2)} />
    <Hotkey keys="l" action="seekStep" value={SEEK_TIME} />
    <Hotkey keys="j" action="seekStep" value={-SEEK_TIME} />
    <Hotkey keys="ArrowUp" action="volumeStep" value={0.05} />
    <Hotkey keys="ArrowDown" action="volumeStep" value={-0.05} />
    <Hotkey keys="0-9" action="seekToPercent" />
    <Hotkey keys="Home" action="seekToPercent" value={0} />
    <Hotkey keys="End" action="seekToPercent" value={100} />
    <Hotkey keys=">" action="speedUp" />
    <Hotkey keys="<" action="speedDown" />
    <Gesture type="tap" action="togglePaused" pointer="mouse" region="center" />
    <Gesture type="tap" action="toggleControls" pointer="touch" />
    <Gesture type="doubletap" action="seekStep" value={-SEEK_TIME} region="left" />
    <Gesture type="doubletap" action="toggleFullscreen" region="center" />
    <Gesture type="doubletap" action="seekStep" value={SEEK_TIME} region="right" />
    <StatusAnnouncer />
    <div className="media-input-feedback">
      <VolumeIndicator.Root className="media-surface media-input-feedback-island media-input-feedback-island--volume">
        <VolumeIndicator.Fill className="media-input-feedback-island__content">
          <VolumeHighIcon className="media-icon media-icon--volume-high" />
          <VolumeLowIcon className="media-icon media-icon--volume-low" />
          <VolumeOffIcon className="media-icon media-icon--volume-off" />
          <VolumeIndicator.Value className="media-input-feedback-island__value" />
        </VolumeIndicator.Fill>
      </VolumeIndicator.Root>
      <StatusIndicator.Root
        actions={['toggleSubtitles', 'toggleFullscreen', 'togglePictureInPicture']}
        className="media-surface media-input-feedback-island media-input-feedback-island--status"
      >
        <div className="media-input-feedback-island__content">
          <CaptionsOnIcon className="media-icon media-icon--captions-on" />
          <CaptionsOffIcon className="media-icon media-icon--captions-off" />
          <FullscreenEnterIcon className="media-icon media-icon--fullscreen-enter" />
          <FullscreenExitIcon className="media-icon media-icon--fullscreen-exit" />
          <PipEnterIcon className="media-icon media-icon--pip-enter" />
          <PipExitIcon className="media-icon media-icon--pip-exit" />
          <StatusIndicator.Value className="media-input-feedback-island__value" />
        </div>
      </StatusIndicator.Root>
      <SeekIndicator.Root className="media-input-feedback-bubble">
        <ChevronIcon className="media-icon media-icon--seek" />
        <SeekIndicator.Value className="media-time" />
      </SeekIndicator.Root>
      <StatusIndicator.Root actions={['togglePaused']} className="media-input-feedback-bubble">
        <PlayIcon className="media-icon media-icon--play" />
        <PauseIcon className="media-icon media-icon--pause" />
      </StatusIndicator.Root>
    </div>
  </Container>
)
