import type { ReactNode } from 'react'
import type { Media } from '@videojs/core/dom'
import type { ThumbnailImage } from './thumbnails'

import { useEffect, useRef, useState } from 'react'
import { css, Global } from '@emotion/react'
import { videoFeatures } from '@videojs/core/dom'
import { createPlayer, useMediaAttach } from '@videojs/react'
import skinCss from '@videojs/react/video/skin.css?inline'

import { RippleSkin } from './skin'
import { startPlayback } from './playback'
import type { AudioStream, PlaybackController } from './playback'
import type { SubtitleStream } from './subtitles'

const player = createPlayer({ features: videoFeatures, displayName: 'RipplePlayer' })

const playerStyle = css`
  position: fixed;
  inset: 0;
  height: 100vh;
  width: 100vw;
  background: #000;

  .media-default-skin {
    height: 100%;
    width: 100%;
  }
  .media-default-skin video {
    height: 100%;
    width: 100%;
    object-fit: contain;
  }
  .ripple-subtitle-canvas {
    position: absolute;
    inset: 0;
    height: 100%;
    width: 100%;
    pointer-events: none;
    z-index: 1;
  }
  .ripple-overlay {
    position: absolute;
    inset: 0;
    pointer-events: none;
    z-index: 2;
  }
  /* The torrent's downloaded regions replace the MSE buffer bar: playback
     evicts the SourceBuffer to a ~80s window, so video.buffered is always a
     sliver of what is actually seekable from disk. */
  .media-slider__buffer {
    display: none;
  }
  /* No preview window where no thumbnail has been generated yet (gap entries
     carry an empty url). */
  .media-slider__preview:has(.media-preview__thumbnail img:not([src])),
  .media-slider__preview:has(.media-preview__thumbnail img[src='']) {
    display: none;
  }
  .ripple-downloaded {
    position: absolute;
    inset: 0;
    pointer-events: none;
  }
  .ripple-downloaded div {
    position: absolute;
    top: 0;
    height: 100%;
    background-color: oklch(from currentColor l c h / 0.2);
  }
  /* A pipeline failure otherwise shows as a black frame under a spinner that
     never resolves, with nothing anywhere saying why. */
  .ripple-error {
    position: absolute;
    inset: auto 0 20%;
    z-index: 3;
    padding: 0 2rem;
    text-align: center;
    color: #fff;
    font-size: 1rem;
    line-height: 1.5;
    text-shadow: 0 0 4px rgba(0, 0, 0, 1);
  }
`

// The video.js skin sizes its controls in rem; ripple's global
// html{font-size:62.5%} would render them at ⅝ scale, so restore a 16px
// root while the full-page player is mounted. The video is object-fit, so
// font-size doesn't affect it - only the skin's rem-based chrome.
const playerRoot = css`
  html {
    font-size: 100%;
  }
`

// Anything at all can end up in playbackError, and a raw DOM Event or a thrown
// string would otherwise be painted over the video as "[object Event]".
const errorMessage = (error: unknown) =>
  error instanceof Error
    ? error.message
    : typeof error === 'string' ? error : 'Playback failed'

// Pushes the real <video> element into the video.js store - a plain
// HTMLVideoElement already satisfies the structural Media contract.
const MediaAttach = ({ video }: { video: HTMLVideoElement | null }) => {
  const setMedia = useMediaAttach()
  useEffect(() => {
    if (!setMedia || !video) return
    setMedia(video as unknown as Media)
    return () => { setMedia(null) }
  }, [video, setMedia])
  return null
}

export type VideoJsPlayerProps = {
  read: (offset: number, size: number) => Promise<ArrayBuffer>
  size: number | undefined
  publicPath: string
  libavWorkerUrl: string
  jassubWorkerUrl: string
  jassubWasmUrl: string
  defaultFontUrl: string
  autoplay?: boolean
  overlay?: ReactNode
  // Extra control-bar entries (e.g. the subtitle menu), right of the rate menu.
  menu?: ReactNode
  // Seekbar hover previews generated by the thumbnail remuxer.
  thumbnails?: ThumbnailImage[]
  // Downloaded regions of the file as [from, to] fractions, drawn on the
  // seekbar in place of the MSE-derived buffer bar.
  downloadedRanges?: [number, number][]
  audioStreamIndex?: number
  onSeek?: (fraction: number) => void
  onSubtitleStreams?: (streams: SubtitleStream[]) => void
  onAudioStreams?: (streams: AudioStream[], selected: number) => void
  onController?: (controller: PlaybackController | null) => void
  // Anything that takes playback down: unsupported codecs, a dead remuxer, a
  // segment the browser refuses. The player shows it too, this is for routes
  // that want their own presentation.
  onPlaybackError?: (error: unknown) => void
}

export const VideoJsPlayer = ({
  read, size, publicPath, libavWorkerUrl, jassubWorkerUrl, jassubWasmUrl,
  defaultFontUrl, autoplay = true, overlay, menu, thumbnails, downloadedRanges,
  audioStreamIndex, onSeek, onSubtitleStreams, onAudioStreams, onController,
  onPlaybackError,
}: VideoJsPlayerProps) => {
  const [video, setVideo] = useState<HTMLVideoElement | null>(null)
  const [canvas, setCanvas] = useState<HTMLCanvasElement | null>(null)
  const [playbackError, setPlaybackError] = useState<unknown>(null)
  const rootRef = useRef<HTMLDivElement>(null)
  const readRef = useRef(read)
  readRef.current = read
  const onSeekRef = useRef(onSeek)
  onSeekRef.current = onSeek
  const onSubtitleStreamsRef = useRef(onSubtitleStreams)
  onSubtitleStreamsRef.current = onSubtitleStreams
  const onAudioStreamsRef = useRef(onAudioStreams)
  onAudioStreamsRef.current = onAudioStreams
  const onControllerRef = useRef(onController)
  onControllerRef.current = onController
  const onPlaybackErrorRef = useRef(onPlaybackError)
  onPlaybackErrorRef.current = onPlaybackError
  // Changing the audio track restarts the whole pipeline; carry the position over.
  const resumeTimeRef = useRef(0)

  // A read that fails once and recovers on a later tick should not leave its
  // message sitting over a video that is playing again.
  useEffect(() => {
    if (!video || !playbackError) return
    const clear = () => setPlaybackError(null)
    video.addEventListener('playing', clear)
    return () => video.removeEventListener('playing', clear)
  }, [video, playbackError])

  // The skin is rendered wholesale, so the downloaded layer is painted into
  // its slider track by hand rather than composed as a React child.
  useEffect(() => {
    if (!downloadedRanges) return
    const track = rootRef.current?.querySelector('.media-slider__track')
    if (!track) return
    let layer = track.querySelector<HTMLElement>('.ripple-downloaded')
    if (!layer) {
      layer = document.createElement('div')
      layer.className = 'ripple-downloaded'
      track.prepend(layer)
    }
    while (layer.childElementCount > downloadedRanges.length) layer.lastElementChild!.remove()
    while (layer.childElementCount < downloadedRanges.length) layer.appendChild(document.createElement('div'))
    downloadedRanges.forEach(([from, to], i) => {
      const seg = layer.children[i] as HTMLElement
      seg.style.left = `${from * 100}%`
      seg.style.width = `${(to - from) * 100}%`
    })
  }, [downloadedRanges, video])

  useEffect(() => {
    if (!video || !canvas || !size) return
    let controller: PlaybackController | undefined
    let cancelled = false
    setPlaybackError(null)
    const fail = (error: unknown) => {
      if (cancelled) return
      console.error('playback failed', error)
      setPlaybackError(error)
      onPlaybackErrorRef.current?.(error)
    }
    ;(async () => {
      try {
        const ctrl = await startPlayback({
          videoElement: video,
          canvasElement: canvas,
          read: (offset, length) => readRef.current(offset, length),
          length: size,
          publicPath,
          libavWorkerUrl,
          jassubWorkerUrl,
          jassubWasmUrl,
          defaultFontUrl,
          audioStreamIndex,
          onReady: () => {
            if (cancelled) return
            if (resumeTimeRef.current > 0) {
              video.currentTime = resumeTimeRef.current
              resumeTimeRef.current = 0
            }
            if (autoplay) video.play().catch(() => {})
          },
          onError: fail,
          onRecovered: () => { if (!cancelled) setPlaybackError(null) },
          onSeek: (fraction) => onSeekRef.current?.(fraction),
          onSubtitleStreams: (streams) => onSubtitleStreamsRef.current?.(streams),
          onAudioStreams: (streams, selected) => onAudioStreamsRef.current?.(streams, selected),
        })
        if (cancelled) ctrl.destroy()
        else {
          controller = ctrl
          onControllerRef.current?.(ctrl)
        }
      } catch (error) {
        fail(error)
      }
    })()
    return () => {
      cancelled = true
      resumeTimeRef.current = video.currentTime
      controller?.destroy()
      onControllerRef.current?.(null)
    }
  }, [video, canvas, size, publicPath, libavWorkerUrl, jassubWorkerUrl, jassubWasmUrl, defaultFontUrl, audioStreamIndex])

  return (
    <div css={playerStyle} ref={rootRef}>
      <Global styles={skinCss} />
      <Global styles={playerRoot} />
      <player.Provider>
        <MediaAttach video={video} />
        <RippleSkin menu={menu} thumbnails={thumbnails}>
          <video ref={setVideo} playsInline />
          <canvas ref={setCanvas} className="ripple-subtitle-canvas" />
          {overlay ? <div className="ripple-overlay">{overlay}</div> : null}
        </RippleSkin>
      </player.Provider>
      {playbackError
        ? <div className="ripple-error">{errorMessage(playbackError)}</div>
        : null}
    </div>
  )
}

export default VideoJsPlayer
