import { readFile } from 'fs/promises'

import { describe, expect, it } from 'vitest'

import { torrentInfoHash } from './torrent-info-hash'

/**
 * The number this produces has to be the SAME one the engine produces, or the share dialog matches
 * against the library and never finds anything, which is the bug that prompted the file.
 *
 * So the anchor case is a REAL torrent with a known infohash rather than a hand-built fixture: a
 * fixture proves the parser is self-consistent and proves nothing about agreeing with libtorrent.
 */

/**
 * A real torrent and the infohash an INDEPENDENT implementation computes for it.
 *
 * Cross-checked against a hand-written bencode walk in python, not against this parser, because a
 * fixture generated by the thing under test proves only that it is self-consistent. The number has
 * to agree with what libtorrent computes or the share dialog matches nothing.
 */
const REAL = {
  path: '/home/banou/downloads/[Erai-raws] Re Zero kara Hajimeru Isekai Seikatsu 4th Season - 13 [1080p CR WEB-DL AVC AAC][MultiSub][E56D4890].torrent',
  infoHash: '4132321f000c268a17938863b4da565b80da71e0',
}

const bencode = (parts: string) => new TextEncoder().encode(parts)

describe('reading an infohash out of a .torrent', () => {
  it('agrees with an independent implementation on a real torrent', async () => {
    const bytes = await readFile(REAL.path).catch(() => null)
    // the file is the owner's rather than the repo's, so its absence must not read as a pass
    if (!bytes) { expect.soft(true, `skipped: ${REAL.path} is not on this machine`).toBe(true); return }
    expect(await torrentInfoHash(new Uint8Array(bytes))).toBe(REAL.infoHash)
  })

  it('finds info wherever it sits in the dictionary', async () => {
    // bencode dict keys are sorted, so `info` is preceded by announce and followed by others
    const doc = bencode('d8:announce9:udp://x:14:infod6:lengthi3e4:name1:ae7:privatei1ee')
    const hash = await torrentInfoHash(doc)
    expect(hash).toMatch(/^[0-9a-f]{40}$/)
  })

  it('hashes the info VALUE and not the whole file', async () => {
    // same info dict, different surrounding keys: the hash must not move
    const a = await torrentInfoHash(bencode('d8:announce5:aaaaa4:infod4:name1:aee'))
    const b = await torrentInfoHash(bencode('d8:announce5:bbbbb4:infod4:name1:ae7:privatei1ee'))
    expect(a).toBe(b)
  })

  it('notices a different info dict', async () => {
    const a = await torrentInfoHash(bencode('d4:infod4:name1:aee'))
    const b = await torrentInfoHash(bencode('d4:infod4:name1:bee'))
    expect(a).not.toBe(b)
  })

  it('walks past nested containers and integers to reach info', async () => {
    const doc = bencode('d13:announce-listll3:onel3:twoeee7:createdi123e4:infod4:name1:aee')
    expect(await torrentInfoHash(doc)).toMatch(/^[0-9a-f]{40}$/)
  })

  /**
   * A file cut off AFTER the info dict still has a valid infohash, and saying so is the point: the
   * hash is of one value, not of the document, so the parser must not fail the whole file for
   * damage that lies beyond the part it hashed.
   */
  it('still reads info from a file truncated after it', async () => {
    const whole = await torrentInfoHash(bencode('d4:infod4:name1:ae7:privatei1ee'))
    const cut = await torrentInfoHash(bencode('d4:infod4:name1:ae'))
    expect(cut).toBe(whole)
  })

  /**
   * Every one of these returns null rather than throwing, because the caller's next move is the
   * same either way: hand the bytes to the engine and let it produce the real message.
   */
  it('returns null for anything that is not a torrent, without throwing', async () => {
    const cases: Record<string, Uint8Array> = {
      empty: new Uint8Array(),
      'not a dict': bencode('l4:infoe'),
      'no info key': bencode('d8:announce5:aaaaae'),
      // the INFO dict itself never closes; a truncated OUTER dict is fine and is covered above
      'unterminated info dict': bencode('d4:infod4:name1:a'),
      'info value missing entirely': bencode('d4:infoe'),
      'string past the end': bencode('d4:info9:abce'),
      'absurd length': bencode('d4:info9999999999999:ae'),
      'html not bencode': bencode('<!doctype html><title>nope</title>'),
      'random bytes': new Uint8Array([0xff, 0x00, 0x13, 0x37]),
    }
    for (const [name, bytes] of Object.entries(cases)) {
      await expect(torrentInfoHash(bytes), name).resolves.toBeNull()
    }
  })

  it('is stable across calls', async () => {
    const doc = bencode('d4:infod4:name4:testee')
    expect(await torrentInfoHash(doc)).toBe(await torrentInfoHash(doc))
  })

  it('produces a 40 character lowercase hex digest, which is what the library stores', async () => {
    const hash = await torrentInfoHash(bencode('d4:infod4:name1:aee'))
    expect(hash).toMatch(/^[0-9a-f]{40}$/)
  })
})
